name: Test and build signed artifacts on release

on:
  pull_request:
    branches: [ master ]

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_IN_KEYSTORE_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_IN_KEYSTORE_ALIAS_PASSWORD }}

jobs:
  build_apk:
    if: contains(github.head_ref, 'dev') == true
    name: Build release artifacts
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: presentation/keystore

      - name: Run tests and build release artifacts
        run: |
          ./gradlew test
          ./gradlew assembleRelease --stacktrace

      - name: Create a directory 
        run: |	
            mkdir -p presentation/releaseApk
            
      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: presentation/releaseApk/app-release.apk
